name: Android Headless Demo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Android emulator (headless) and install APK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          emulator-options: -no-window -no-audio -gpu swiftshader_indirect
          force-avd-creation: true
          disable-animations: true
          script: |
            adb wait-for-device
            adb install -r apks/demo.apk
            adb shell input keyevent 82
            sleep 60

      - name: Upload log artifact
        uses: actions/upload-artifact@v4
        with:
          name: emulator-log
          path: /home/runner/.android/avd || true
